/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Grafica;

import Datos.Correo;
import Datos.Empleado;
import Datos.Empresa;
import fecha.Fecha;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author 203pc1
 */
public class PanelEnviar extends javax.swing.JPanel {
    Empresa email;
    int usuarioValidado;
    DefaultComboBoxModel modelo;
    // se pone fuera por que se usa en varios sitios
    Fecha f= new Fecha();
    
    public PanelEnviar() {
        initComponents();
        
    }

    /*public PanelEnviar(Empresa email, int usuarioValidado) {
        initComponents();
        this.email=email;
        this.usuarioValidado=usuarioValidado;
    }*/
    
    public PanelEnviar(Empresa email, int usuarioValidado) {
        //NO OLVIDAR initComponents(); al crear constructor
        initComponents();
        this.email=email;
        this.usuarioValidado=usuarioValidado;
        //SIEMPRE LO ULTIMO
        //this.usuarioValidado=usuarioValidado;
        cargarEmpleados();
        
        txtFecha.setText(f.visualizar());
    }
    
    public void cargarEmpleados(){
        modelo = new DefaultComboBoxModel();
        //se recorre y se van guardando
        for (int i=0; i<email.getMisEmpleados().size();i++){
            modelo.addElement(email.getMisEmpleados().get(i));
        }
        //se carga en el combo box
        cmbDestinatario.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbDestinatario = new javax.swing.JComboBox();
        txtFecha = new javax.swing.JTextField();
        txtAsunto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaTexto = new javax.swing.JTextArea();
        bntEnviar = new javax.swing.JButton();
        bntCancelar = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(100, 100));
        setPreferredSize(new java.awt.Dimension(767, 767));

        jLabel1.setText("Destinatario");

        jLabel2.setText("Fecha");

        jLabel3.setText("Asunto");

        jLabel4.setText("Texto");

        txtFecha.setEnabled(false);

        txaTexto.setColumns(20);
        txaTexto.setRows(5);
        jScrollPane1.setViewportView(txaTexto);

        bntEnviar.setText("Enviar");
        bntEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntEnviarActionPerformed(evt);
            }
        });

        bntCancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(bntEnviar)
                        .addGap(62, 62, 62)
                        .addComponent(bntCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtAsunto, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAsunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntEnviar)
                    .addComponent(bntCancelar))
                .addGap(60, 60, 60))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bntEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntEnviarActionPerformed
      
        //COMPROBAR QUE EL ASUNTO NO ESTE VACIO
        
        String asunto=txtAsunto.getText();
        String texto=txaTexto.getText();
        Correo correo;
        int opcion=0;
        //controlar errores con showMessageDialog
        if(asunto.equals("")){
            JOptionPane.showMessageDialog(this, "El Asunto no puede estar vacio");
            //recuperar foco en txt asunto
            txtAsunto.requestFocus();
        } 
        //controlar errores con showConfirmDialog
        if (texto.equals("")){
           opcion= JOptionPane.showConfirmDialog(this, "El texto esta vacio ¿Enviar?", 
                   "Error", JOptionPane.YES_NO_OPTION);
           
  
        }
        if (opcion==0) {
        
        //en varias lineas
        //int posicion=cmbDestinatario.getSelectedIndex();
        //empleado e=(Empleado)modelo.getElementAt(posicion);
        Empleado e=(Empleado)modelo.getElementAt(cmbDestinatario.getSelectedIndex());
        //Se crea el correo (FIJARSE EN EL CONSTRUCTOR DE CORREO PARAMETROS Y ORDEN)
        correo=new Correo(asunto, texto, usuarioValidado,f);
        //correo=new Correo(asunto, texto, USUARIOVALIDADO,f);
        // se manda correo (METODO CREADO EN CLASE CORREO)
        // no hay que actualizar email
        e.recibirCorreo(correo);
        } else {
             txaTexto.requestFocus();
        }
        
    }//GEN-LAST:event_bntEnviarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntCancelar;
    private javax.swing.JButton bntEnviar;
    private javax.swing.JComboBox cmbDestinatario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txaTexto;
    private javax.swing.JTextField txtAsunto;
    private javax.swing.JTextField txtFecha;
    // End of variables declaration//GEN-END:variables
}
