/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Grafica;

import Datos.Empresa;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author pc
 */
public class VentanaUsuario extends javax.swing.JFrame {
    int usuarioValidado;
     PanelEnviar penviar; 
     pnlLeer pleer;
     
    private Empresa email;
    public VentanaUsuario(Empresa email, int usuarioValidado) {
        this.email=email;
        this.usuarioValidado=usuarioValidado;
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/Usuarios.png")).getImage());
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        mnuEnviar = new javax.swing.JMenuItem();
        mnuLeer = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setPreferredSize(getMaximumSize());
        getContentPane().setLayout(new java.awt.FlowLayout());

        jMenu1.setText("Usuario");

        jMenuItem2.setText("Datos Personales");
        jMenu1.add(jMenuItem2);

        mnuEnviar.setText("Enviar Correo");
        mnuEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEnviarActionPerformed(evt);
            }
        });
        jMenu1.add(mnuEnviar);

        mnuLeer.setText("Bandeja de Entrada");
        mnuLeer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLeerActionPerformed(evt);
            }
        });
        jMenu1.add(mnuLeer);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Desconectar");

        jMenuItem5.setText("Salir");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        new Validacion(email).setVisible(true);
        dispose();
        pack();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void quitarPaneles(){
    try{
        // GUARDAR EMAIL ANTES DE BORRAR PANEL PARA GUARDAR CAMBIOS
        // CON PANELES NO HACE FALTA POR SER UN OBJETO SI ES UN PRIMITIVO SSSIII
       this.email = penviar.email;
       this.remove(penviar);
    }catch(Exception e){}
    try{
        // GUARDAR EMAIL ANTES DE BORRAR PANEL PARA GUARDAR CAMBIOS
        // CON PANELES NO HACE FALTA POR SER EMAIL UN OBJETO SI ES UN PRIMITIVO SSII
       this.email = pleer.email;
       this.remove(pleer);
    }catch(Exception e){}
    
}
    private void mnuEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEnviarActionPerformed
        // TODO add your handling code here:
        quitarPaneles();
        penviar=new PanelEnviar(email, usuarioValidado);
        this.add(penviar);
        pack();
    }//GEN-LAST:event_mnuEnviarActionPerformed

    private void mnuLeerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLeerActionPerformed
        // TODO add your handling code here:
         quitarPaneles();
        pleer=new pnlLeer(email, usuarioValidado);
        this.add(penviar);
        pack();
    }//GEN-LAST:event_mnuLeerActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem mnuEnviar;
    private javax.swing.JMenuItem mnuLeer;
    // End of variables declaration//GEN-END:variables
}
