/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Grafica;

import Datos.Empresa;
import javax.swing.JFrame;

/**
 *
 * @author 203pc1
 */
public class VentanaAdministrador extends javax.swing.JFrame {
  private Empresa email;
  pnAlta palta;
  pnlModificaciones pnlModifi;
    //public VentanaAdministrador( Empresa email,)
    public VentanaAdministrador( Empresa email) {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.email=email;
             
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        mnuModificarUsuario = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Administrador");
        getContentPane().setLayout(new java.awt.FlowLayout());

        jMenu1.setText("Administrador");

        jMenuItem1.setText("Altas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        mnuModificarUsuario.setText("Modificar");
        mnuModificarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuModificarUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(mnuModificarUsuario);

        jMenuItem7.setText("Baja");
        jMenu1.add(jMenuItem7);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Usuario");

        jMenuItem4.setText("Datos Personales");
        jMenu2.add(jMenuItem4);

        jMenuItem6.setText("Enviar correo");
        jMenu2.add(jMenuItem6);

        jMenuItem5.setText("Bandeja de entrada");
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Desconectar");

        jMenuItem3.setText("Salir como administrador");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuModificarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuModificarUsuarioActionPerformed
        // Cambiar entre ventanas paneles
        quitarPaneles();
        pnlModifi=new pnlModificaciones(email);
        this.add(pnlModifi);
        pack();
    }//GEN-LAST:event_mnuModificarUsuarioActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
     
        new Validacion(email).setVisible(true);
        dispose();
        pack();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        quitarPaneles();
        palta=new pnAlta(email);
        this.add(palta);
        pack();
    }//GEN-LAST:event_jMenuItem1ActionPerformed
private void quitarPaneles(){
    try{
        // GUARDAR EMAIL ANTES DE BORRAR PANEL PARA GUARDAR CAMBIOS
        // CON PANELES NO HACE FALTA POR SER UN OBJETO SI ES UN PRIMITIVO SSSIII
       this.email = palta.email;
       this.remove(palta);
    }catch(Exception e){}
    try{
        // GUARDAR EMAIL ANTES DE BORRAR PANEL PARA GUARDAR CAMBIOS
        // CON PANELES NO HACE FALTA POR SER EMAIL UN OBJETO SI ES UN PRIMITIVO SSII
       this.email = pnlModifi.email;
       this.remove(pnlModifi);
    }catch(Exception e){}
    
}
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem mnuModificarUsuario;
    // End of variables declaration//GEN-END:variables
}
